name:
  desktop: ó°Ÿ€
  downloads: ó°‰
  videos: ó°•§
  music: ó°š
  documents: ó°ˆ™
  pictures: ó°‹«
  templates: ó°°
  public: ó°€
  doc: ó°ˆ™
  node_modules: î—º
  .trash: ó°©¹
  .github: ó°Š¤
  .gitmodules: ó°Š¢
  .gitignore: ó°Š¢
  .editorconfig: ó°’“
  .cargo: ó±˜—
  a.out: ó°†
  license.txt: ó±•´
  .zshrc: ó°†
  package-lock.json: ó°Œ
  package.json: ó°Œ
  user-dirs.dirs: ó±¿
  nvim: ó°•·
  share: ó°’—
  bin: ó±¿
  config: ó±¿
extension:
  md: ó°‹¼
  json: ó°Œ
  go: î˜§
  hs: ó°²’
  rs: ğŸ¦€
  tar: ó°›«
  gz: ó°›«
  zip: ó°›«
  rar: ó°›«
  png: ó°‹©
  jpg: ó°‹©
  jpeg: ó°‹©
  svg: ó°œ¡
  gif: ó°µ¸
  xlsx: ó°ˆ›
  yml: ó°…©
  toml: ó°…©
  otf: ó°‰¿
  ttf: ó°‰¿
  list: ó°‰¹
  conf: ó°’“
  xml: ó°—€
  txt: ó°ˆš
  csv: ó°ˆ®
  lua: ó°¢±
  log: ó°†ˆ
  desktop: ó°±
filetype:
  dir: ó°°
  file: ó°ˆ”
  pipe: ó°‡®
  socket: ó°†¨
  executable: ó°†
  symlink-dir: ó±§®
  symlink-file: ó±ª“
  device-char: î˜
  device-block: ó°œ«
  special: ï‹œ
